# Generated by Django 4.2 on 2024-09-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_pv_post_uv'),
        ('comment', '0003_comment_aim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='aim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='评论文章'),
        ),
    ]
